import type { Metadata } from "next";
import { Inter, Orbitron } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });
const digital = Orbitron({
    subsets: ["latin"],
    variable: "--font-digital",
});

export const metadata: Metadata = {
    title: "Magic Post",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html suppressHydrationWarning lang="vi">
            <body
                className={cn(
                    "bg-background font-sans antialiased",
                    inter.variable,
                    digital.variable,
                )}
            >
                <main>{children}</main>
            </body>
        </html>
    );
}
